security: add trivy scanning workflow
coder/enterprise-images pull request #195
Opened 2023-02-06 16:16 UTC by deansheather

Adds trivy scanning to the build workflow, uploading results as an artifact and to the GitHub security tab.

2023-02-07 10:24 UTC, johnstcn approved these changes

2023-02-07 11:28 UTC, johnstcn requested changes
Think we need to add a workflow step to install `trivy`.

2023-02-07 23:09 UTC, deansheather commented
This can be merged without resolving code scanning results, then we can go through afterwards and resolve them.

2023-02-08 05:22 UTC, spikecurtis approved these changes

2023-02-08 09:22 UTC, johnstcn approved these changes

2023-02-08 09:27 UTC, merged